appId: com.ravinderz.aptly
env:
  APP_ENV: development
  API_BASE_URL: http://localhost:3000
  TEST_USER_PHONE: '+919876543210'
  TEST_USER_OTP: '123456'
  TIMEOUT: 30000
  APP_SCHEME: aptly
  PLATFORM: ios
  DEVICE: 'iPhone 15'

# Development-specific settings
debug: true
verbose: true

# Test user accounts for development
testUsers:
  resident:
    phone: '+919876543210'
    otp: '123456'
    name: 'Test Resident'
    email: 'resident@test.com'
    apartment: 'A-101'
  admin:
    phone: '+919876543211'
    otp: '123456'
    name: 'Test Admin'
    email: 'admin@test.com'
    apartment: 'A-102'
  security:
    phone: '+919876543212'
    otp: '123456'
    name: 'Test Security'
    email: 'security@test.com'
    apartment: 'Security Office'
  manager:
    phone: '+919876543213'
    otp: '123456'
    name: 'Test Manager'
    email: 'manager@test.com'
    apartment: 'Manager Office'

# Society configuration for testing
testSociety:
  name: 'Test Society'
  code: 'TEST123'
  address: '123 Test Street'

# API endpoints for development
apiEndpoints:
  auth: '/api/auth'
  users: '/api/users'
  societies: '/api/societies'
  visitors: '/api/visitors'
  community: '/api/community'
