appId: com.ravinderz.aptly
env:
  APP_ENV: production
  API_BASE_URL: https://api.aptly.com
  TEST_USER_PHONE: '+919876543210'
  TEST_USER_OTP: '123456'
  TIMEOUT: 60000
  APP_SCHEME: aptly
  PLATFORM: ios
  DEVICE: 'iPhone 15'

# Production-specific settings (minimal testing)
debug: false
verbose: false

# Limited test user accounts for production
testUsers:
  resident:
    phone: '+919876543210'
    otp: '123456'
    name: 'Prod Test Resident'
    email: 'test.resident@aptly.com'
    apartment: 'TEST-101'

# Society configuration for production testing
testSociety:
  name: 'Production Test Society'
  code: 'PROD123'
  address: '123 Production Street'

# API endpoints for production
apiEndpoints:
  auth: '/api/v1/auth'
  users: '/api/v1/users'
  societies: '/api/v1/societies'
  visitors: '/api/v1/visitors'
  community: '/api/v1/community'

# Production safety settings
safetyChecks:
  enabled: true
  maxTestDuration: 300000 # 5 minutes max
  dataCleanup: true
