appId: com.ravinderz.aptly
env:
  APP_ENV: staging
  API_BASE_URL: https://staging-api.aptly.com
  TEST_USER_PHONE: '+919876543210'
  TEST_USER_OTP: '123456'
  TIMEOUT: 45000
  APP_SCHEME: aptly
  PLATFORM: ios
  DEVICE: 'iPhone 15'

# Staging-specific settings
debug: false
verbose: false

# Test user accounts for staging
testUsers:
  resident:
    phone: '+919876543210'
    otp: '123456'
    name: 'Staging Resident'
    email: 'resident@staging.aptly.com'
    apartment: 'A-101'
  admin:
    phone: '+919876543211'
    otp: '123456'
    name: 'Staging Admin'
    email: 'admin@staging.aptly.com'
    apartment: 'A-102'
  security:
    phone: '+919876543212'
    otp: '123456'
    name: 'Staging Security'
    email: 'security@staging.aptly.com'
    apartment: 'Security Office'
  manager:
    phone: '+919876543213'
    otp: '123456'
    name: 'Staging Manager'
    email: 'manager@staging.aptly.com'
    apartment: 'Manager Office'

# Society configuration for staging
testSociety:
  name: 'Staging Test Society'
  code: 'STAGE123'
  address: '123 Staging Street'

# API endpoints for staging
apiEndpoints:
  auth: '/api/v1/auth'
  users: '/api/v1/users'
  societies: '/api/v1/societies'
  visitors: '/api/v1/visitors'
  community: '/api/v1/community'
